version: '3.1'
services:
  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql1/data/
    container_name: postgresql1
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explorewithme
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  stats-dto:
    build: ./stats-service/dto
    image: explorewithme_stats_dto_image
    container_name: stats-dto

  stats-server:
    build: ./stats-service/server
    image: explorewithme_stats_server_image
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
      - stats-dto
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explorewithme
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - DRIVER_CLASS_NAME=org.postgresql.Driver

  stats-client:
    build: ./stats-service/client
    image: explorewithme_stats_client_image
    container_name: stats-client
    ports:
      - "8989:8989"
    depends_on:
      - stats-dto

  ewm-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql2/data/
    container_name: postgresql2
    ports:
      - "5700:5400"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  ewm-service:
    build: ./main-service
    image: explorewithme_main_service_image
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - STATS_CLIENT_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5400/explorewithme
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - DRIVER_CLASS_NAME=org.postgresql.Driver
