version: '3.1'
services:
  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_db_cont
    ports:
      - "4321:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db_cont
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

  ewm-common:
    build: common/
    container_name: ewm_common_cont

  ewm-service:
    build: main-service/main-server/
    container_name: ewm_service
    ports:
      - "8282:8282"
    depends_on:
      - ewm-db
      - ewm-common
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
      - DRIVER_CLASS_NAME=org.postgresql.Driver

  stats-server:
    build: stats-service/
    container_name: stats_server_cont
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
      - ewm-common
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats
      - DRIVER_CLASS_NAME=org.postgresql.Driver

  ewm-gateway:
    build: main-service/gateway/
    container_name: ewm_gateway_cont
    ports:
      - "8080:8080"
    depends_on:
      - ewm-common
      - ewm-service
      - stats-server
    environment:
      - MAIN_SERVER_URL=http://ewm-service:8282
      - STATS_SERVER_URL=http://stats-server:9090
