version: '3.1'
services:
  ewm-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql1/data/
    container_name: postgresql1
    ports:
      - "6542:5423"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql2/data/
    container_name: postgresql2
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  ewm-common:
    build: ./common
    image: ewm_common_image
    container_name: ewm-common

  ewm-service:
    build: ./main-service/main-server
    image: ewm-service_image
    container_name: ewm-service
    ports:
      - "8181:8181"
    depends_on:
      - stats-db
      - ewm-common
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - DRIVER_CLASS_NAME=org.postgresql.Driver

  stats-server:
    build: ./stats-service
    image: ewm_stats_server_image
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
      - ewm-common
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - DRIVER_CLASS_NAME=org.postgresql.Driver

  ewm-gateway:
    build: ./main-service/gateway
    image: ewm_gateway_image
    container_name: ewm-gateway
    ports:
      - "8080:8080"
    depends_on:
      - ewm-common
      - ewm-service
      - stats-server
    environment:
      - MAIN_SERVER_URL=http://ewm-service:8181
      - STATS_SERVER_URL=http://stats-server:9090
